### ISSUE TITLE
Create a new release at PyPI

### ISSUE THREAD

**Issue by icemac** [zopefoundation/z3c.checkversions#10]
The current release is not compatible with a recent version of `setuptools`.

Please create a release on PyPI or give me (`icemac`)  the needed permissions so I can do it myself.

cc: @ccomb (Could not add you as assignee as you do not belong to the zopefoundation organization.)

**Comment by mgedmin** [comment]
You're now a PyPI owner of z3c.checkversions.

**Comment by ccomb** [comment]
Thanks @mgedmin for adding @icemac on pypi as I don't expect to maintain this package in the short or middle term

**Comment by icemac** [comment]
Thank you. I just released https://pypi.org/project/z3c.checkversions/1.0/
