### ISSUE TITLE
Installation - working as intended?

### ISSUE THREAD

**Issue by jugmac00** [zopefoundation/z3c.checkversions#13]
When I install z3c.checkversions with pip(x), and try to run `checkversions` then I get a Traceback as zc.buildout is not installed.

zc.buildout is listed as "extra_require", not as "install_requires".

Is this working as intended? Why would I install a tool when I cannot use it afterwards?

```
jugmac00@jugmac00-XPS-13-9370:~/Projects/bliss_deployment/work/source/bliss.git$ checkversions versions.cfg
Traceback (most recent call last):
  File "/home/jugmac00/.local/pipx/venvs/z3c.checkversions/lib/python3.6/site-packages/z3c/checkversions/buildout.py", line 16, in <module>
    from zc.buildout.buildout import Buildout
ModuleNotFoundError: No module named 'zc'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/jugmac00/.local/bin/checkversions", line 10, in <module>
    sys.exit(main())
  File "/home/jugmac00/.local/pipx/venvs/z3c.checkversions/lib/python3.6/site-packages/z3c/checkversions/main.py", line 80, in main
    from . import buildout
  File "/home/jugmac00/.local/pipx/venvs/z3c.checkversions/lib/python3.6/site-packages/z3c/checkversions/buildout.py", line 18, in <module>
    raise ImportError("zc.buildout is not installed! \n"
ImportError: zc.buildout is not installed! 
If you're in a buildout environment,
enable the buildout extra requirement like this:
eggs = z3c.checkversions [buildout]
```

After manually installing zc.buildout into the same virtualenv it worked.

**Comment by jugmac00** [comment]
After re-reading the readme, I think the intention was
- that the installation via pip only works for packages within current environment
- that the installation via buildout was meant to check buildout config files

The readme is not that clear about this.

When I want to check for outdated versions in the current environment, I usually use `pip list --outdated` which possibly was not available back in the days when z3c.checkversions was created.

There are several possible things to do now:
- leave it as it is or
- improve the exception message (as it only refers to a buildout installation) and/or
- improve the readme and/or
- install zc.buildout by default!

Opinions?

**Comment by mgedmin** [comment]
I'm feeling -0.5 for always depending on zc.buildout, but the traceback should be replaced with a clear error message

    sys.exit("buildout versions.cfg support is an optional feature; to enable it pip install z3c.checkversions[buildout]")

The current error message already says this, which I've only just now noticed, but the clear explanation is hidden by numerous tracebacks that should be suppressed.

**Comment by jugmac00** [comment]
@mgedmin Thank you for your input.

Actually, I never had the need to optionally install a package, so the syntax
`pip install z3c.checkversions[buildout]`
was new to me.

The current error message only applies to installation via buildout, so I'd like to see the error message amended.

I do not think that the current chained is too distracting, I'd leave it as it is (except amending the message).

Well, I'd preferred the "user friendly" way and always install `zc.buildout` so the tool could be used for all use cases, but I bow to the majority.

I'll try to come up with a pr.

**Comment by mvoppen** [comment]
Just a question: The above mentioned <code>pip list --outdated</code> gives on my system the following:
```
$ bin/pip3.7 list --outdated
Exception:
Traceback (most recent call last):
  File "/var/local/www/zope/zope4/lib/python3.7/site-packages/pip/_internal/cli/base_command.py", line 143, in main
    status = self.run(options, args)
  File "/var/local/www/zope/zope4/lib/python3.7/site-packages/pip/_internal/commands/list.py", line 138, in run
    packages = self.get_outdated(packages, options)
  File "/var/local/www/zope/zope4/lib/python3.7/site-packages/pip/_internal/commands/list.py", line 149, in get_outdated
    dist for dist in self.iter_packages_latest_infos(packages, options)
  File "/var/local/www/zope/zope4/lib/python3.7/site-packages/pip/_internal/commands/list.py", line 150, in <listcomp>
    if dist.latest_version > dist.parsed_version
TypeError: '>' not supported between instances of 'Version' and 'Version'
```
I suppose that's not the normal result. Where can I report that?

**Comment by mvoppen** [comment]
ok, this problem seems to be handled here: https://github.com/pypa/pip/issues/5757

**Comment by jugmac00** [comment]
Ah well, forgot to close this issue - see #15
