### ISSUE TITLE
Misses new 'zope.*' releases

### ISSUE THREAD

**Issue by tseaver** [zopefoundation/z3c.checkversions#7]
When updating https://github.com/zopefoundation/zopetoolkit, the `bin/checkversions` script finds other packages:

```
pip=8.1.2
setuptools=24.0.2
virtualenv=15.0.2
zc.buildout=2.5.2
```

But misses new releases of `zope.*` packages (its main purpose in life, AFAIK).

**Comment by icemac** [comment]
``bin/checkversions -v buildout.cfg`` also shows the packages where the script was not able to find a newer version.

**Comment by tseaver** [comment]
OK, my bad:  I had thought that the `zopetoolkit` buildout wired up all the eggs in its `[versions]` section to be checked without passing any command-line arguments.
